Add support to make the APM yum/apt repo configuration optional
claranet/puppet-newrelic pull request #5
Opened 2017-08-10 12:39 UTC by russwhelan

2017-08-10 12:48 UTC, roland-bashton commented
Change looks good. The more options  the better. :+1:

2017-08-11 08:38 UTC, craigwatson commented on manifests/params.pp
> +      $newrelic_enable_repo   = 'true'
These should be unquoted as they're booleans

2017-08-11 08:43 UTC, craigwatson requested changes
`true` and `false` should be unquoted as they're booleans

2017-08-11 10:09 UTC, craigwatson approved these changes

2017-08-11 10:11 UTC, merged